name: chinese_chess
description: A ChineseChess game developed by Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cchess: ^0.0.7
  cchess_engine: ^0.0.1
  engine:
    path: plugins/engine

  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  logging: ^1.2.0
  file_picker: ^6.1.1
  shirne_dialog: ^4.5.0
  fast_gbk: ^1.0.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.6
  provider: ^6.1.1
  path_provider: ^2.1.5

  audioplayers: ^6.4.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4

  # Social Login
  google_sign_in: ^6.0.2  # Using a version compatible with Firebase
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

# flutter pub run icons_launcher:create
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/icon/icon_foreground.png"
    ios:
      enable: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Specify which platforms the app supports
flutter_platform_ios: true
flutter_platform_android: true
flutter_platform_web: false
flutter_platform_linux: false
flutter_platform_macos: false
flutter_platform_windows: false

# The following section is specific to Flutter.
flutter:

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/skins/woods/
    - assets/skins/stones/
    - assets/images/
    - assets/sounds/
