# iOS deployment target
platform :ios, '14.0'

# Disable warnings
inhibit_all_warnings!

# For Firebase compatibility
use_frameworks! :linkage => :static

target 'ChineseChessRN' do
  # Firebase pods
  pod 'Firebase', '~> 10.15.0'
  pod 'FirebaseCore', '~> 10.15.0'
  pod 'FirebaseAuth', '~> 10.15.0'
  pod 'FirebaseFirestore', '~> 10.15.0'
  pod 'FirebaseStorage', '~> 10.15.0'
  pod 'FirebaseAnalytics', '~> 10.15.0'

  post_install do |installer|
    # Configuration for all targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

        # Fix for Xcode 15 build issues
        if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end

        # Disable bitcode as it's deprecated in Xcode 14+
        config.build_settings['ENABLE_BITCODE'] = 'NO'

        # Fix for non-modular includes in framework modules
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = "YES"

        # Fix for arm64 architecture issues
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
